### ISSUE TITLE
On Android when we do trim in Release mode App crashes. On IOS the trimmer thumbnail bar has red part with errors also cannot trim in IOS

### ISSUE THREAD

**Issue by faizanrafiq7** [sbis04/video_trimmer#110]

**Comment by listade** [comment]
Same problem

**Comment by Gicminos** [comment]
I believe these are two separate issues. On behalf of the second part "On IOS the trimmer thumbnail bar has red part with errors also cannot trim in IOS", here are some additional details as the same happens to me:

![image](https://user-images.githubusercontent.com/9993624/121782781-2709e600-cba3-11eb-9697-a5f6cbee61f4.png)

Here is the error in console:
```
Flutter: Attempted to composite external texture sources using the software backend. This backend is only used on simulators. This feature is only available on actual devices where OpenGL or Metal is used for rendering.
Flutter: Attempted to composite external texture sources using the software backend. This backend is only used on simulators. This feature is only available on actual devices where OpenGL or Metal is used for rendering.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _CastError was thrown building:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ThumbnailViewer.build.<anonymous closure>.<anonymous closure> (package:video_trimmer/src/thumbnail_viewer.dart:63:58)
flutter: #1      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
flutter: #2      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1213:28)
flutter: #3      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1226:55)
flutter: #4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535:19)
flutter: #5      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1219:12)
flutter: #6      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
flutter: #7      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1889:59)
flutter: #8      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:912:15)
flutter: #9      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1889:14)
flutter: #10     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
flutter: #11     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:484:5)
flutter: #12     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239:19)
flutter: #13     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:282:19)
flutter: #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
flutter: #15     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
flutter: #16     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
flutter: #18     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
flutter: #19     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1574:12)
flutter: #20     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1483:20)
flutter: #21     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636:7)
flutter: #22     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
flutter: #23     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
flutter: #24     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
flutter: #25     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
flutter: #26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #27     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #28     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
flutter: #32     _invoke (dart:ui/hooks.dart:163:10)
flutter: #33     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
flutter: #34     _drawFrame (dart:ui/hooks.dart:126:31)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

flutter doctor (iOS only):

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Connected device (2 available)
```

**Comment by sbis04** [comment]
@faizanrafiq7  the Android device release mode error solution can be found [here](https://github.com/sbis04/video_trimmer/issues/107#issuecomment-845698655), try it once and let me know if that works. 

For the iOS error, as it is similar to issue #105, so I would encourage you to follow that thread.

**Comment by sbis04** [comment]
Closing this issue, track the iOS related issue here: #105
