### ISSUE TITLE
The app stops on : flutter run --release when saving the trimmed video

### ISSUE THREAD

**Issue by kahdichienja** [sbis04/video_trimmer#127]
``` DateTime: Aug 15, 2021 - 09:09:43
I/flutter (15561): Formatted: Aug15,2021-09:09:43
I/flutter (15561): Creating
I/flutter (15561): Retrieved Trimmer folder
I/flutter (15561): Start: 0:00:00.000000 & End: 0:00:01.820000
I/flutter (15561): /data/user/0/com.example.videotrim/app_flutter/Trimmer/
I/flutter (15561): OUTPUT: .mp4
D/flutter-ffmpeg(15561): Running FFmpeg with arguments: [-ss, 0:00:00.000000, -i, /data/user/0/com.example.videotrim/cache/file_picker/VID-20210811-WA0002.mp4, -t, 0:00:01.820000, -avoid_negative_ts, make_zero, -c:a, copy, -c:v, copy, /data/user/0/com.example.videotrim/app_flutter/Trimmer/VID-20210811-WA0002_trimmed:Aug15,2021-09:09:43.mp4].
E/AndroidRuntime(15561): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(15561): Process: com.sosnetworks.maberrr, PID: 15561
E/AndroidRuntime(15561): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(15561): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(15561): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(15561): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(15561): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(15561): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(15561): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(15561): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(15561): Caused by: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/com.sosnetworks.maberrr-zOO2TvvEh9H3F0cpfVARtA==/base.apk!/lib/arm64-v8a/libmobileffmpeg.so": 0
E/AndroidRuntime(15561): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
E/AndroidRuntime(15561): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime(15561): 	at java.lang.System.loadLibrary(System.java:1667)
E/AndroidRuntime(15561): 	at com.arthenica.mobileffmpeg.Config.<clinit>(Unknown Source:146)
E/AndroidRuntime(15561): 	at com.arthenica.mobileffmpeg.Config.f(Unknown Source:0)
E/AndroidRuntime(15561): 	at com.arthenica.mobileffmpeg.c.d(Unknown Source:2)
E/AndroidRuntime(15561): 	at c.a.a.a.a.a(Unknown Source:31)
E/AndroidRuntime(15561): 	at c.a.a.a.a.doInBackground(Unknown Source:2)
E/AndroidRuntime(15561): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(15561): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(15561): 	... 3 more

**Comment by KishoreTechJays** [comment]
If flutter_ffmpeg release builds on Android fail with the following exception, make sure that mavenCentral() is defined as a repository in your build.gradle and it is listed before jcenter().

**Comment by kahdichienja** [comment]
Okay let me work on it, then notify

**Comment by kahdichienja** [comment]
ok were specifically in th graddle,

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath 'com.google.gms:google-services:4.3.8'
        classpath
"org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

**Comment by kahdichienja** [comment]
it worked bro.. am happy, thanks

**Comment by kahdichienja** [comment]
is there a way to get *thumbnail* ???

**Comment by sbis04** [comment]
@kahdichienja you can use the [video_thumbnail](https://pub.dev/packages/video_thumbnail) plugin to achieve that

**Comment by kahdichienja** [comment]
Awesome, thanks!
