### ISSUE TITLE
outputPath is not existed

### ISSUE THREAD

**Issue by husen-hn** [sbis04/video_trimmer#145]
in the example app when I save video after trim, I gave outputPath but this path does not exist and the Preview player can not play this video. I try to upload this path I get an error and when I print this code I get 0 `print(File(outputPath).lengthSync())` log=> `0`. 

`video_trimmer: ^0.6.0`

`flutter version 2.5.0`

Preview player log:
```bash
E/ExoPlayerImplInternal(13234):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
E/ExoPlayerImplInternal(13234):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(13234):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(13234):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(13234):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FragmentedMp4Extractor, Mp4Extractor, FlvExtractor, FlacExtractor, WavExtractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal(13234):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal(13234):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1027)
E/ExoPlayerImplInternal(13234):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
E/ExoPlayerImplInternal(13234):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(13234):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(13234):       at java.lang.Thread.run(Thread.java:919)
E/flutter (13234): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (13234):
I/ExoPlayerImpl(13234): Release 989a200 [ExoPlayerLib/2.14.1] [vbox86p, Google Pixel 3a Android 10 API 29, Genymobile, 29] [goog.exo.core]
D/SurfaceUtils(13234): disconnecting from surface 0xcc7c5808, reason disconnectFromSurface

```

**Comment by wiaam-kareem** [comment]
this issue is happening to me also the output path is not working

**Comment by sbis04** [comment]
Please try with the latest version of this package (`v1.0.0`), and let me know if it solves the issue.

**Comment by husen-hn** [comment]
@sbis04 
```bash
I/flutter ( 4235): TAGAX start to save
I/flutter ( 4235): DateTime: Dec 5, 2021 - 13:52:55
I/flutter ( 4235): Formatted: Dec5,2021-13:52:55
I/flutter ( 4235): TAGAX end save
W/es.sofficia( 4235): Accessing hidden method Lsun/misc/Unsafe;->
compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/flutter ( 4235): Exists
I/flutter ( 4235): Retrieved Trimmer folder
I/flutter ( 4235): Start: 0:00:00.000000 & End: 0:00:10.000000
I/flutter ( 4235): /data/user/0/com.sm.sfficial/app_flutter/Trimmer/
I/flutter ( 4235): OUTPUT: .mp4
I/flutter ( 4235): Loading ffmpeg-kit-flutter.
D/ffmpeg-kit-flutter( 4235): FFmpegKitFlutterPlugin started listening to events on 
io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation@dde1f1b.
I/flutter ( 4235): Loaded ffmpeg-kit-flutter-android-https-x86-4.5.0-lts.
W/ffmpeg-kit-flutter( 4235): ResultHandler can not send event {FFmpegKitExecuteCallbackEvent=
{createTime=1638730375609, startTime=1638730375618, sessionId=1, type=1, command=
-ss 0:00:00.000000 -i /data/user/0/com.smes.smesofficial/cache/file_picker/VID_20211102_030320.mp4
 -t 0:00:10.000000 -avoid_negative_ts make_zero -c:a copy -c:v copy /data/user/0/com.smes.smesofficia
l/app_flutter/Trimmer/VID_20211102_030320_trimmed:Dec5,2021-13:52:55.mp4}} on a null event sink.
```

for this code:
```dart
_saveVideo() {
    setState(() {
      _progressVisibility = true;
    });
    try {
      print('TAGAX start to save');
      _trimmer.saveTrimmedVideo(
        startValue: _startValue,
        endValue: _endValue,
        onSave: (outputPath) {
          setState(() {
            _progressVisibility = false;
          });
          debugPrint('TAGAX OUTPUT PATH: $outputPath');
          print('TAGAX ${File(outputPath!).existsSync()}');
          pvController.pickedVideo.value = File(outputPath);
          Get.back();
        },
      );
      print('TAGAX end save');
    } catch (e) {
      print('TAGAX $e');
    }
  }
```

**Comment by husen-hn** [comment]
@sbis04 I tested this problem completely and this error is from FFmpeg.[ u need to update to the latest version](https://stackoverflow.com/questions/70261076/flutter-ffmpeg-kit-flutter-resulthandler-can-not-send-event-on-a-null-event-sink)

**Comment by husen-hn** [comment]
@wiaam-kareem for now just replace this with the current FFmpeg in packages's YAML file to resolve it. 

```yaml
 ffmpeg_kit_flutter:
    git:
      url: https://github.com/shilangyu/ffmpeg-kit
      ref: development-flutter
      path: prebuilt/bundle-flutter-lts/default
```

**Comment by sadaqatkarimi** [comment]
onSave is not call in version 1.0.0
