### ISSUE TITLE
Can't access the video after trimmed

### ISSUE THREAD

**Issue by estermabel** [sbis04/video_trimmer#184]
I'm having a problem where I can't access the video after it's trimmed. I'm sending the output path of the trimmed video for the video_player lib to show it in my screen. But it returns an error saying the path wasn't found.

```
I/flutter (27758): DateTime: 16 de nov de 2022 - 14:25:00
I/flutter (27758): Formatted: 16denovde2022-14:25:00
I/flutter (27758): Exists
I/flutter (27758): Retrieved Trimmer folder
I/flutter (27758): Start: 0:00:21.497000 & End: 0:00:36.115000
I/flutter (27758): /data/user/0/com.valemobi.flut.feed/app_flutter/Trimmer/
I/flutter (27758): OUTPUT: .mp4
I/flutter (27758): Loading ffmpeg-kit-flutter.
D/ffmpeg-kit-flutter(27758): FFmpegKitFlutterPlugin stopped listening to events.
D/ffmpeg-kit-flutter(27758): FFmpegKitFlutterPlugin started listening to events on io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation@5ef9f65.
I/flutter (27758): Loaded ffmpeg-kit-flutter-android-https-arm-v7a-neon-4.5.0-lts.
I/emobi.flut.fee(27758): Background concurrent copying GC freed 11797(921KB) AllocSpace objects, 50(4008KB) LOS objects, 6% free, 83MB/89MB, paused 177us total 118.074ms
W/System  (27758): A resource failed to call close.
I/chatty  (27758): uid=10151(com.valemobi.flut.feed) FinalizerDaemon identical 4 lines
W/System  (27758): A resource failed to call close.
I/flutter (27758): FFmpeg process exited with state COMPLETED and rc 0
I/flutter (27758): FFmpeg processing completed successfully.
I/flutter (27758): Video successfuly saved
I/flutter (27758): VIDEO EDITED PATH: /data/user/0/com.valemobi.flut.feed/app_flutter/Trimmer/image_picker2777393902162931345_trimmed:16denovde2022-14:25:00.mp4
I/ExoPlayerImpl(27758): Init dbfcce1 [ExoPlayerLib/2.18.1] [a01core, SM-A013M, samsung, 29]
I/ExoPlayerImpl(27758): Release b37e694 [ExoPlayerLib/2.18.1] [a01core, SM-A013M, samsung, 29] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
D/RefBase (27758): RefBase: Explicit destruction, weak count = 0 (in 0x645f2604)
W/RefBase (27758): CallStack::getCurrentInternal not linked, returning null
W/RefBase (27758): CallStack::logStackInternal not linked
I/GPUAUX  (27758): [AUX]~GPUAUXContext:77: destory: 0x699da330
E/BufferQueueProducer(27758): [SurfaceTexture-0-27758-2] cancelBuffer: BufferQueue has been abandoned
I/chatty  (27758): uid=10151(com.valemobi.flut.feed) JNISurfaceTextu identical 5 lines
E/BufferQueueProducer(27758): [SurfaceTexture-0-27758-2] cancelBuffer: BufferQueue has been abandoned
D/SurfaceUtils(27758): disconnecting from surface 0x689bf808, reason disconnectFromSurface
E/ExoPlayerImplInternal(27758): Playback error
E/ExoPlayerImplInternal(27758):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(27758):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
E/ExoPlayerImplInternal(27758):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
E/ExoPlayerImplInternal(27758):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(27758):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(27758):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(27758):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.MalformedURLException: no protocol: /data/user/0/com.valemobi.flut.feed/app_flutter/Trimmer/image_picker2777393902162931345_trimmed:16denovde2022-14:25:00.mp4
E/ExoPlayerImplInternal(27758):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:373)
E/ExoPlayerImplInternal(27758):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
E/ExoPlayerImplInternal(27758):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(27758):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
E/ExoPlayerImplInternal(27758):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(27758):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(27758):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(27758):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(27758):   Caused by: java.net.MalformedURLException: no protocol: /data/user/0/com.valemobi.flut.feed/app_flutter/Trimmer/image_picker2777393902162931345_trimmed:16denovde2022-14:25:00.mp4
E/ExoPlayerImplInternal(27758):       at java.net.URL.<init>(URL.java:601)
E/ExoPlayerImplInternal(27758):       at java.net.URL.<init>(URL.java:498)
E/ExoPlayerImplInternal(27758):       at java.net.URL.<init>(URL.java:447)
E/ExoPlayerImplInternal(27758):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:515)
E/ExoPlayerImplInternal(27758):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:367)
E/ExoPlayerImplInternal(27758):       ... 7 more
```

**Comment by estermabel** [comment]
The problem was that the path was being returned with ":" inside it.
