### ISSUE TITLE
ios records 14 s and 15 seconds of video dragging.

### ISSUE THREAD

**Issue by wanglili6** [sbis04/video_trimmer#207]
Hello, ios records 14 s and 15 seconds of video dragging. I have the following questions, please help me to take a look:

**Comment by wanglili6** [comment]
Unsupported operation: Infinity or NaN toInt

When the exception was thrown, this was the stack: 
#0      double.toInt (dart:core-patch/double.dart)
#1      _ScrollableTrimViewerState._onStartDragged (package:video_trimmer/src/trim_viewer/scrollable_viewer/scrollable_trim_viewer.dart:528:64)
#2      _ScrollableTrimViewerState._onDragUpdate (package:video_trimmer/src/trim_viewer/scrollable_viewer/scrollable_trim_viewer.dart:492:9)
#3      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:483:55)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#5      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:483:7)
#6      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:330:9)
#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#19     _invoke1 (dart:ui/hooks.dart:164:13)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)

**Comment by karamatpkid** [comment]
Same issue is here

**Comment by Gaurav-pix** [comment]
Same issue here

**Comment by furkancetintass** [comment]
I was able to solve this issue by adding this parameter

type: ViewerType.fixed
